### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IzzySoft** [IanField90/DevStat#18]
What license is your project using, @IanField90 – and do you still maintain it?

**Comment by IanField90** [comment]
@IzzySoft I've just update it to have a license file.
I'm not maintaining it much anymore, beyond updating the build chain. It's got the features that I was after adding - with the key aim of not requiring any permissions. I see that now that permissions are using a request/grant style that this could change.

**Comment by IzzySoft** [comment]
Thanks, Ian! I read that as "not actively developed, but still maintained" – thanks, that answers my question! Thanks also for adding the license!

In case you're curious for the background of your question: I was "checking" my entire repo for missing details (here: license). Your app [is in there](https://apt.izzysoft.de/fdroid/index/apk/uk.co.ianfield.devstat) :smiley:
