### ISSUE TITLE
APK missing on release 2.4.5

### ISSUE THREAD

**Issue by IzzySoft** [IanField90/DevStat#19]
Could you please attach the APK to this release, like it was done for past ones? Thanks!

**Comment by IzzySoft** [comment]
@IanField90 any chance?

**Comment by IzzySoft** [comment]
@IanField90 are you still there?

**Comment by IanField90** [comment]
I've not got plans to do this, no. Most other versions will have an aab from now on.

**Comment by IzzySoft** [comment]
Thanks for letting me know – I'll decommission it then, as I cannot handle `*.aab`s. For background: Your app was [listed here](https://apt.izzysoft.de/fdroid/index/apk/uk.co.ianfield.devstat) since 8/2017. That's a "simple binary F-Droid repo", and fdroidserver cannot deal with App Bundles. So I'll have to mark the app "stale" there now as I cannot update it anymore :cry:

**Comment by IanField90** [comment]
I see. Do you have any metrics on it to know if anyone's using it?
I can probably keep an APK uploaded for future versions, but not this one retrospectively.

**Comment by IzzySoft** [comment]
Thanks! And no need for "historical ones" – just the latest and future ones would suffice.

No, no analytics here. And since the version currently online in my repo is quite old, I doubt there will be many downloads (I can check the web server logs for 1 or 2 weeks back:

* 8 downloads this week
* 19 downloads the week before

Not bad for a 4 year old.

**Comment by IzzySoft** [comment]
12 this week so far – which makes an average of 13 (rather more, as the current log just covers 4 days). Now imagine there were a more recent version available :wink:

**Comment by IanField90** [comment]
Should be sorted with 2.4.7 :)

**Comment by IzzySoft** [comment]
Yay, thanks a lot! I just triggered an update manually, and it was pulled fine (will show up with the next sync tomorrow) – so I've also re-enabled auto-update via tags.

Need to remember tooting about the update once it's there, to raise attention: "After a long sabbatical, DevStat is back with an update from 2019's 2.4.0 to a very recent 2.4.7 – enjoy!" :smiley:

**Comment by BraINstinct0** [comment]
@IzzySoft Since 2.4.7 AND 2.4.8 are up on your repo, I think the 
`Note: This app will not be updated anymore as the author` [does no longer provide APK files](https://github.com/IanField90/DevStat/issues/19#issuecomment-888916302).
should now be edited out?

**Comment by IzzySoft** [comment]
@BraINstinct0 Oh, right you are – removed that and while on it also added the icon. Maybe @IanField90 would like to add [the link to it](https://apt.izzysoft.de/fdroid/index/apk/uk.co.ianfield.devstat) in the Readme – next to the statement that the app is no longer on Play? There'd even be [a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) that can be used for that :wink:
